spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sys?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Haijun521
  mvc:
    view:
      prefix: /
      suffix: .html
